# Generated by Django 6.0.3 on 2026-04-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
